### ISSUE TITLE
Generic cache module

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#10]
Generic cache module

The module will for given a physical block address signal the availability ofthe corresponding Block_data. If it is available, the caller may access the data. Otherwise it may instruct the module to get the data from backing storage (the module could do that on its own as a side-effect of the availability check but I'd like to keep it explicit for now). The cache replacement strategy is fixed and uses LRU at the moment. An interface that makes it possible to employ different strategies might be useful in the future.

It implements the following interface:

**`available`** returns true if the data-block for the given physical block address is available within the cache.

**`data`** returns the data-block for the given physical block address. Must only be called when data_available has returned true.

**`acceptable`** returns true if the cache is able to accept a request for new block to cache.

**`submit_request`** submits the request to cache the block given by the physical block address. Must only be called when acceptable returned true.

**`peek_generated_primitive`** returns true if the cache has outstanding I/O primitives

**`take_generated_primitive`** returns the next pending primitive. Must only be called when peek_generated_primitive has returned a valid primitive.

**`mark_completed_primitive`** marks the given primitive as completed. At this point the data is available within the cache.

The module's first user will be the MMU module and depending on its requirments the interface might change.

**Comment by nfeske** [comment]
Thanks for putting the state of the discussion in writing.

**Comment by cnuke** [comment]
@m-stein I've implemented the module in SPARK now (please see 97ec4d1276ca590f8909a). It would be nice if you could talk a look.

**Comment by m-stein** [comment]
@cnuke Looks cool to me so far :-), A lot of work. I'm through with cbe-cache.ads/adb but cannot continue with the other files before 16:30 pm.

**Comment by cnuke** [comment]
Thanks for the feedback, I'll change the code according to your remarks. Take your time, I'll will look at the rest tomorrow.
