### ISSUE TITLE
Translation module

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#12]
Translation module

The Translation module translate a virtual block address to a physical block address. It therefor walks the tree starting from a given root node. For every level it will generate a primitive that requests the block data containing the physical block address for the next level.

It implements the following interface:

**`primitive_acceptable`** returns true if the Translation is able to handle the given translation request.

**`submit_primitive`** adds the given translation request to the module.

**`peek_completed_primitive`** returns a completed or invalid primitive in case the translation has not finished yet.

**`discard_completed_primitive`** removes the completed translation request.

**`peek_generated_primitive`** returns the next pending or invalid primitive in case all required primitives were already issued.

**`drop_generated_primitive`** removes the generated primitive.

**`mark_generated_primitive_complete`** marks the given primitive as completed. If all primitives belonging to a translation request are complete, the request is marked as _complete_ and **`peek_completed_primitive`** will return a valid primitive.

Although this definition talks about _primitives_, the natural argument for this module would be a `virtual block address` and `physical block address` would be the response.

On that account, the current prototype contains a bunch of helper methods for other modules, e.g. **`get_physical_block_addresses`** for dumping all phyiscal block address of the current translation request or **`height`** which just returns the height of the current tree, which are not strictly necessary for final version of the module. It also features methods that inhibit translation, e.g. **`suspend`** and **`resume`**, which is used to prevent handling read block request for virtual block address that are currently rewritten.

**Comment by m-stein** [comment]
The translation module is now translated to SPARK and works (my cbe_sparkify_translation_module branch, based on the last working state of cnuke/cbe_wip). Note, that I had to adapt the LSC-SHA256-4K to be pure which isn't upstream yet.

**Comment by m-stein** [comment]
The VBD module (a wrapper for the translation module for the virtual block device tree) is now translated to SPARK and works (see my branch ``cbe``).
