### ISSUE TITLE
Write-back module

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#13]
Write-back module

The write-back module handles updating and writing a new branch for a given _virtual block address_ (_vba_) and thereby a 4K block of data. It copies all old branch nodes and updates the corresponding _physical block address_ (_pba_) in each entry within each new node. It will also instruct the the crypto module to encrypt the new leave (data) node. After the update process is finished all new nodes will be written to disk.

The write-back module will generate several different primitives. The first one is a crypto primitive that is allotted to encryption by the crypto module.The second is a cache primitive that is used to collect the old nodes from the cache module. The third and last primitive is the I/O primitive that is used by the I/O module for writing the new nodes to disk. That being said, it will only issue I/O primitives after all crpyto and cache primitives have been completed.

It implements the following interface:

**`primitive_acceptable`** returns true if no write-back operation is in progress, otherwise false is returned.

**`submit_primitive`** creates a new write-back operation. Since the module will need to update the existing nodes, it receives a list of _pba_ for the old nodes as well as the starting _pba_ of the new nodes (for the moment new nodes are allocated in a contiguous order). 

**`peek_completed_primitive`** returns a completed or invalid primitive in case the write-back operation has not yet finished.

**`peek_completed_root`** returns the _pba_ of the new root node for the given completed primitive. (This _pba_ is then stored in the new super-block.)

**`drop_completed_primitive`** removes the completed translation request.

**`peek_generated_primitive`** returns the next pending or invalid primitive in case all required primitives were already issued.

**`peek_generated_data`** returns a reference to the block data associated with the generated primitive. _(Since we cannot use this approach in SPARK the method will replace by a procedure that receives the block data reference from the out-side.)_

**`drop_generated_primitive`** removes the generated crypto and cache primitive.

**`mark_generated_primitive_complete`** marks the given primitive as completed. So far it is only used for crypto primitives as cache primitives are nevered marked but used directly by the **`copy_and_update`** procedure.

**`peek_generated_io_primitive`** returns the next pending I/O primitive or invalid primitive in case all primitives were already issued.

**`peek_generated_io_data`** returns a reference to the block data associated with the generated primitive. _(Since we cannot use this approach in SPARK the method will replace by a procedure that receives the block data reference from the out-side.)_

**`drop_generated_io_primitive`** removes the generated I/O primitive.

**`mark_generated_io_primitive_complete`** marks the given I/O primitive as completed.

**`copy_and_update`** takes the block data of an old node from the cache module and copies it to its internal block data node where it will update the _pba_ in the corresponding entry.

Its stands to reason if we really need different functions/procedures for the different primitives as it makes the interface larger but it matches the signal-line analogy nicely.

**Comment by nfeske** [comment]
The translation to SPARK can be found on my branch https://github.com/nfeske/cbe/commits/cbe
