### ISSUE TITLE
Scriptable test environment

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#15]
The test environment shall detect regression bugs by sequentially executing a set of test scripts that mainly consist of three steps each:
1) Reset the CBE block component to a desired initial state (super blocks, trees, hashes) given via XML
2) Execute a set of commands given in XML at the CBE front-end
3) Compare the resulting state of the CBE block component (super blocks, trees, hashes) reported via XML with the expected state

**Comment by m-stein** [comment]
A first fully functional version of the VBD report in the CBE block component: https://github.com/m-stein/cbe/commit/bfab665c5dba69b9c8667ea37e8aab8a04f21b52

**Comment by nfeske** [comment]
Wow! This was really quick. We outlined the plan just yesterday after all. The code looks very fine, too. :-)

**Comment by m-stein** [comment]
Thanks :)

**Comment by m-stein** [comment]
@cnuke I have merged my most recent state to your cbe_wip branch. It reports the VBD state and writes it from the config. It's not dynamically configurable so far. I've added some clean-up commits. I hope you're fine with them? The branch is cbe_test:

f856a10 cbe_block: remove dead code
5a58111 cbe_block: no global statics
0a389d0 cbe: change run script to trigger free error
8997a6a cbe: print pba on hash mismatch
ff028c6 fixup 'cbe_block: report VBD and write state from config' (expanding reporter, configure report)
5a4cd7b cbe_block: report VBD and write state from config

**Comment by m-stein** [comment]
@cnuke I considered removing the "initialize" functionality as it can be replaced via an appropriate config and the "dump" feature as it can be replaced via a verbose report_rom. What do you think?

**Comment by cnuke** [comment]
@m-stein Thanks! I would still prefer to keep (any) kind of programmatical way to generate the tree at least for now. Otherwise it becomes cumbersome to test different sizes / topologies, especially if the tree is reasonably sized.

**Comment by m-stein** [comment]
@cnuke Of course.

**Comment by m-stein** [comment]
There's now a first working version of the test/cbe component (an adaption of the test/init component). Currently it is used in run/cbe_test to evaluate a small R/W test twice in the runtime init. It's time to write some more sophisticated test scripts. My cbe_test branch:

0856e63 test/cbe: raise log performance
e95b7bc test/cbe: execute same test twice
300881f test/cbe: beautify member variables
80d5dbb test/cbe: original init test
2af0a63 cbe_test.run: execute same test twice
760a074 cbe_test.run: original test in sub-init
19fbc68 cbe_block: remove dead code
2d543bc cbe_block: no global statics
cc03e71 fixup "cbe_block: report VBD and write state from config" (configure report)
6ef1cc1 fixup 'cbe_block: report VBD and write state from config' (expanding reporter, configure report)
ede680c cbe_block: report VBD and write state from config

**Comment by cnuke** [comment]
Thanks, I cherry-picked your commits and added them to my current [cnuke/cbe_wip](https://github.com/cnuke/cbe/commits/cbe_wip) branch. Please base any further development on this branch.

**Comment by m-stein** [comment]
Alright, thanks! Should I proceed creating more sophisticated test scripts now or may we leave it with this until the CBE has reached a more complete state?

**Comment by cnuke** [comment]
Let's post-pone that to next week.

**Comment by m-stein** [comment]
This issue is fixed on current master.
