### ISSUE TITLE
Block-I/O module

### ISSUE THREAD

**Issue by nfeske** [cbe-project/cbe#16]
The translation of @cnuke's `Block_io` module from C++ to SPARK can be found at my branch https://github.com/nfeske/cbe/commits/cbe

**Comment by m-stein** [comment]
@nfeske As this issue is fixed on current master, may I ask you to close it?

**Comment by m-stein** [comment]
And thanks again for the much needed help back then ;)

**Comment by nfeske** [comment]
Sure. Thanks for cleaning up the issues.
