### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by jklmnn** [cbe-project/cbe#17]
After an offline discussion we decided to bring the code base to a consistent code style. The base line is a check with `gnatpp` where I will provide the relevant flags soon. Furthermore I suggest to use our [style guide](https://github.com/Componolit/ada-style/wiki/Style-Guide). A hard requirement for the code style is to be compliant with Muen.

**Comment by senier** [comment]
@jklmnn Can you please add the flags to the style guide.

**Comment by jklmnn** [comment]
There is also the question if 80 or 120 character long lines should be used. The first would be compatible to most Ada environments (including Muen and the runtime) while the latter is often more convenient without being to long for modern displays (even with two columns). Since the CBE will most probably run on Muen within [Gneiss](../../../Componolit/Gneiss) which already enables 120 character lines on Muen, I'd suggest to go with 120.

**Comment by senier** [comment]
I'd prefer 120 characters, too.

**Comment by cnuke** [comment]
I don't mind either way - 120 colums is fine.

**Comment by jklmnn** [comment]
For now the best configuration of the pretty printer seems to be:
```
gnatpp \
    --name-mixed-case \
    --enum-mixed-case \
    --type-mixed-case \
    --pragma-mixed-case \
    --indent-continuation=3 \
    --max-line-length=120 \
    --insert-blank-lines \
    --split-line-before-op \
    --par-threshold=1 \
    --call-threshold=3 \
    --vertical-named-aggregates \
    --vertical-case-alternatives \
    --comments-gnat-beginning
```
Although it doesn't completely fulfill our style guide. Especially in some bigger context, e.g. whole function/procedure declarations. For example our function declaration is:
```Ada
function Fun (Arg1 : Type1;
              Arg2 : Type2) return Type3;
```
while the pp outputs
```Ada
function Fun
   (Arg1 : Type1;
    Arg1 : Type2)
   return Type3;
```

**Comment by cnuke** [comment]
Using those flags leads to some unexpected(?) fun regarding commentation:

```Ada
package Foobar with
   Spark_Mode
 is
   …
   function Foo
      (V : Type)
       return Type2 is (V.Bar);
      --
      -- Comment Foo
      --
   procedure Bar (V : out Type);
   --
   -- Comment Fnord
   --
   procedure Fnord 
      (V1 : Type;
       V2  : Type2);
      --
      -- Comment Func
      -- 
   function Func …
```

**Comment by jklmnn** [comment]
In vim you can set
```vim
autocmd FileType ada setlocal expandtab shiftwidth=3 softtabstop=3 colorcolumn=120
```
to have the correct indentation in Ada code.

**Comment by jklmnn** [comment]
> Using those flags leads to some unexpected(?) fun regarding commentation:
> 
> ```ada
> package Foobar with
>    Spark_Mode
>  is
>    …
>    function Foo
>       (V : Type)
>        return Type2 is (V.Bar);
>       --
>       -- Comment Foo
>       --
>    procedure Bar (V : out Type);
>    --
>    -- Comment Fnord
>    --
>    procedure Fnord 
>       (V1 : Type;
>        V2  : Type2);
>       --
>       -- Comment Func
>       -- 
>    function Func …
> ```

The problem seems to be that gnatpp seems to assume that doc comments are after the commented entity (which is also supported by the way it inserts empty lines).
To be honest I doubt that we can use gnatpp as an automatic tool.

**Comment by jklmnn** [comment]
@cnuke @m-stein I refactored the style in https://github.com/Componolit/cbe/commit/76b1821092d1bf2040310fc68bc24364a2093f1b.

**Comment by cnuke** [comment]
Well, that would rule out `gnatpp` for automated use indeed. Thanks for looking into it anyway and thanks
for doing the refactoring - I'll incorporate it soon (probably some time next week).

**Comment by m-stein** [comment]
@jklmnn That looks really clean! Thanks! I will try to enable all compiler style checking in the Genode repo, so the style stays enforced. Or have you planned to do so?

**Comment by jklmnn** [comment]
I have not yet planned to do so and I'd appreciate it if you're working on this. I would recommend adding `-gnatyyBdM120Sux` for now. It might be too restrictive for the current code to compile but we should then see if the restriction collides with our style guide or if we want to change the code and use it.

**Comment by m-stein** [comment]
Thanks for the (admittedly funny looking) flag line! The first it complains about is that we should use "and then" in any place were an "if" checks multiple conditions instead of using simple "and".

I would keep this behavior as clearly defining the order of condition checking appears benificial to me. Any objections?

**Comment by senier** [comment]
We discussed that with AdaCore a while back. You almost never have any benefits from using `and` over `and then`. Consequently, we adopted the rule to use `and then` exclusively.

**Comment by m-stein** [comment]
@jklmnn  Sorry, that I come up with this a little bit delayed: Is there a reason that the re-factoring does much more than what is required by the compiler? For instance, code like this ...
```
function Discard_Snapshot (
   Active_Snaps : in out Snapshots_Type;             
   Curr_Snap_Id :        Snapshot_Id_Type)
return Boolean;

function Request_Primitive_Invalid
return Request_Primitive_Type
is (
   Req         => Request.Invalid_Object,
   Prim        => Primitive.Invalid_Object,
   Tag         => Tag_Invalid,
   In_Progress => False);
```
... was changed to this ...
```
function Discard_Snapshot (Active_Snaps : in out Snapshots_Type;             
                           Curr_Snap_Id :        Snapshot_Id_Type) return Boolean;

function Request_Primitive_Invalid return Request_Primitive_Type is
   (Req => Request.Invalid_Object, Prim => Primitive.Invalid_Object, Tag => Tag_Invalid, In_Progress => False);
```
It was on purpose that I consistently used the above style, even if it consumes more vertical space: Not only is the second version, IMO, much harder to read but it also unnecessarily introduces lines longer than 80 chars. Both versions compile with the GNAT flags you posted.

I would like to revert such changes and only apply style fixes enforced by the GNAT flags.

**Comment by jklmnn** [comment]
My refactoring was based on what gnatpp generated, so I threw all files into gnatpp and then fixed whatever it did wrong. So I actually never saw the original style of most parts of the code.

That being said the function `Discard_Snapshot` is exactly as we defined it in our [style guide](https://github.com/Componolit/ada-style/wiki/Style-Guide#function) and I'd like to keep that style consistently in the code even if it breaks the 80 lines.

For `Request_Primitive_Invalid` I understand your concern. Although I'd prefer
```Ada
function Request_Primitive_Invalid return Request_Primitive_Type is
   (Req         => Request.Invalid_Object,
    Prim        => Primitive.Invalid_Object,
    Tag         => Tag_Invalid,
    In_Progress => False);
```

**Comment by m-stein** [comment]
@jklmnn Your comment made me rethink the matter because my initial goal, when we talked about coding style, was not to find and apply a comprehensive set of rules but to only adapt to those enforced by the compiler that, I assume, are broadly accepted by the Ada community and have a clear benefit.

When it comes to a comprehensive coding style, I see the point that you have an own version and would like to apply it to this code also, but please try to see it from my perspective: My intuition tells me that whatever coding style is now promoted for Ada/SPARK in Genode will most probably last - even if it is more for conformity than for its properties. I therefore think that, for the Genode project, it would be better to adapt to a coding style that is based on a broad consent that evolved over long time like the [GNAT coding style](https://gcc.gnu.org/onlinedocs/gnat-style.pdf) or the [Ada Style Guide](https://upload.wikimedia.org/wikipedia/commons/7/7c/Ada_Style_Guide.pdf).

**Comment by m-stein** [comment]
I must admit that I have missed the initial discussion in this issue as I didn't receive any mail notifications. I would have expressed my concern much earlier.

"A hard requirement for the code style is to be compliant with Muen."
May I ask what are the implications of this statement?

**Comment by nfeske** [comment]
(I have no dog in the fight in this discussion. I also have not checked back with any participant off-line)

While I appreciate the attention to coding-style consistency, discussions likes these bear the potential or discouragement, which I sense in @m-stein's response.

Please let us not split hair over minor white-space policing. We have found a wide agreement of most of the style questions. The remaining points are a matter of taste.

@jklmnn Please recognize the social awkwardness of the situation. If @m-stein was seeking the inclusion of a patch into an existing Componolit code base, it would go without saying that your style and taste is law. It would be a nobrainer to adjust the whitespacing however _you_ want.

However, here the situation is different: We have created a new code base from scratch. You contributed _no single line_ of code to it. Yet, you want to impose your taste upon the original authors. This reeks of disrespect. Consequently, the discussion reaches an emotional level, which is not constructive.

Let us focus on the stuff that matters: building rock-solid and powerful software in a cooperative and fun spirit for all of us.

**Comment by senier** [comment]
To avoid any further discussions on the topic IMHO we should follow @m-stein's suggestion to use the established [Ada Style Guide](https://upload.wikimedia.org/wikipedia/commons/7/7c/Ada_Style_Guide.pdf) and follow it without exception. Code authors are encouraged to ensure that their own code complies to the style when committing to the repo.

**Comment by m-stein** [comment]
> Please let us not split hair over minor white-space policing. We have found a wide agreement of most of the style questions. The remaining points are a matter of taste.
>
> Let us focus on the stuff that matters: building rock-solid and powerful software in a cooperative and fun spirit for all of us.

I totally agree with this, thanks @nfeske! I would also be fine with @senier's suggestion.

In case that everyone is fine with the GNAT flags posted by @jklmnn, I have pushed commits on my [genode/cbe](https://github.com/m-stein/genode/commits/cbe) and [cbe/cbe](https://github.com/m-stein/cbe/commits/cbe) branches. They only change what is necessary to re-enable compiling with the new flags, so, the question of a comprehensive coding style remains a separate topic. My cbe/cbe branch is based on the most recent cbe/cbe branch of @cnuke. All "cbe style" commits (now separate for documentation purpose) can be squashed together to one.

**Comment by jklmnn** [comment]
IIrc you wanted to shorten the line length, so you could to change the GNAT flags to `-gnatyyBdmSux`, which uses the default of 79 chars.

**Comment by m-stein** [comment]
Admittedly, I wasn't up for a hard 80-chars limit as I had your experiences regarding this in mind and also saw 80 chars still as soft limit that should be ignored only in rare cases. But now I gave the hard limit a try and I think it isn't a big problem yet. The additional commits can be found on my [genode/cbe](https://github.com/m-stein/genode/commits/cbe) and [cbe/cbe](https://github.com/m-stein/cbe/commits/cbe) branches. At least in the context of the CBE, it didn't lead to obscure constructs IMO. However, I don't have strong feelings about that: If it turns out to become problematic in the future, we can as well relax it again.

**Comment by cnuke** [comment]
I pushed [cbe/cbe](https://github.com/m-stein/cbe/commits/cbe), which contains @m-stein style adjustments.

**Comment by m-stein** [comment]
I re-based the commit "cbe_block: write initial state to linux file" on my cbe/cbe branch (which is based on the most recent state of cnuke/cbe/cbe).

**Comment by m-stein** [comment]
@jklmnn This issue seems to be solved so far. May I ask you to close it?
