### ISSUE TITLE
Manage crypto block-buffers outside of the CBE library

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#18]
The crypto block buffers are currently part of the crypto-module object of the CBE library. This was fine when the actual encryption/decryption was also done inside this module. But now, the CBE shall support encryption/decryption via an external entity through its crypto back-end interface. Thus we should move the buffers out of the library and hand them in only when needed, respectively reference specific items inside the buffers via an index. This avoids unnecessarily copying data blocks when communicating with the external crypto entity and streamlines the CBE interface.

**Comment by m-stein** [comment]
On my cbe/cbe branch I have finished the first step and moved the buffers out of the library to the main object of our cbe server. Next, I'd like to streamline the CBE interface accordingly, and then adapt also our cbe vfs to the new version.

**Comment by m-stein** [comment]
On my cbe/cbe branch, a first complete version can be found. **This version is only a proposal and not meant to be applied broadly yet**. These are the parts that are new in the CBE-library interface:
* ``Execute``: received 2 additional in-out parameters - references to the plain and cipher block-data buffer that are used to communicate between the CBE-internal crypto module and an external crypto back-end. The memory for both buffers is managed by the world outside the CBE library. Layout and size are given by the CBE-library. The management of the buffer contents is completely controlled by the CBE-library.
* ``Obtain_Client_Data``: replaced data and progress out parameters by 2 new out parameters, the data index and whether the data index is valid. The procedure does no longer copy the client data itself but merely tells the outside world which slot of the crypto plain block-data buffer contains the client data. If the data index is marked invalid via the second parameter, there is no client data available. 
* ``Crypto_Cipher_Data_Required``: replaces ``Crypto_Data_Required``. The new procedure returns a request and a data index. If the request is invalid, the data index is useless. The request does no longer contain a valid tag. The tag can therefore be used by the outside world to remember the data index to be able to reference the operation in the following procedures.
* ``Crypto_Cipher_Data_Requested``: replaces ``Obtain_Crypto_Plain_Data``. The new procedure does not hand-out any data any more (as this is already achieved via the data index returned by Crypto_Cipher_Data_Required). It merely acknowledges that the outside world has requested the encryption of the plain data referenced by the only in parameter of the function - the data index that corresponds tothe request.
* ``Supply_Crypto_Cipher_Data``: The progress out parameter was removed as it was unnecessary. The request and data in parameters were replaced by 2 new in parameters, the data index and whether the data index is valid. If the data index marked as invalid, this means that the request failed and the data index is useless. 
* ``Crypto_Plain_Data_Required``: replaces ``Has_Crypto_Data_To_Decrypt``. Same as Crypto_Cipher_Data_Required but for decryption requests.
* ``Crypto_Plain_Data_Requested``: replaces ``Obtain_Crypto_Cipher_Data``. Same as Crypto_Cipher_Data_Requested but for decryption requests.
* ``Supply_Crypto_Plain_Data``: Same as Supply_Crypto_Cipher_Data but for decryption requests.

The new interface is exemplarily used in Genodes CBE server with an "external" crypto entity.

**Comment by cnuke** [comment]
Thanks for doing the leg work of cleaning up the interface, I appreciate that. I'll adapt the VFS plugin and see how it works out.

**Comment by m-stein** [comment]
This issue is fixed on current master.
