### ISSUE TITLE
CBE refine superblock handling

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#20]
- [ ] Handle reading superblock information internally and notify the user when the CBE is ready to be used.
- [ ] Pass out the information the TA needs when the superblock was written to disk.

*(This is mostly the preservation of a discussion @m-stein and I had today and exists for future reference.)*

*Recap: at the moment the library gets handed in a piece of memory that contains the superblocks as well as the location of the most recent one. Obtaining those superblocks is part of the setup phase and is handled by the arbiter. Writing of the superblocks, however, is done from within the library (see the `Sync_Superblock` module) where it will directly write on of the first N 4096 blocks that cover the superblock area. Reading the blocks was done by the arbiter so that initializing the library was only done in case valid superblock(s) where read from the block device.*

*I would like to remove the writing part from the library and also move it to the arbiter to gain more flexibility on where and how to store the superblock data. Whenever the run-time was instructed to secure the current superblock it will give the superblock back to the outside which then is in charge of making it persistent.*

*That change would require to modify the `CBE.Library` interface but would make the steps needed for the `CBE` to work more explicit.*

In contrast to that we could also move the setup phase into the `CBE.Library`, basically introducing a `Select_superblock` module, which would simplify the setup phase for the user of the library. This, however, would make it more difficult to select other superblocks and would hardcode how and where to store the superblocks. That being said, with this change in place, the user would simply initialize the CBE and wait for it to become ready, i.e. something along the lines of `CBE.Initialize` followed by `CBE.Ready`.

**Comment by cnuke** [comment]
I updated the issue to reflect the current state of discussion.

**Comment by m-stein** [comment]
@cnuke Thanks for documenting our discussion!
