### ISSUE TITLE
CI support for proving CBE

### ISSUE THREAD

**Issue by senier** [cbe-project/cbe#21]
We [just added](https://travis-ci.com/Componolit/cbe) support for automatically running `gnatprove` for the CBE code base on TravisCI. This should allow us to prove the code easily in a reproducible environment.

@cnuke: I'd like to enable this for the upstream cbe-project/cbe repository so that we can spot open verification conditions early. I used your `cbe_wip` branch for now, but I'm not sure whether this is the right basis to use as an initial staging branch. Could you please have a look? (cherry-picking the CI commit should be straightforward).

**Comment by cnuke** [comment]
Thanks for setting up the CI, much appreciated. For testing that the CI works the `cbe_wip` branch is fine but it contains some *work-in-progress* commits I would like to clean up. I will prepare a clean `cbe` branch which we can use a initial `staging` branch.

**Comment by senier** [comment]
> Thanks for setting up the CI, much appreciated. For testing that the CI works the `cbe_wip` branch is fine but it contains some _work-in-progress_ commits I would like to clean up.

That's what I was assuming from the branch name ;-) Consequently, I didn't look into the proof output too closely - I will do that and create another topic issue regarding proof once we have a staging branch.

> I will prepare a clean `cbe` branch which we can use a initial `staging` branch.

Cool, thanks! I'll take care of adapting the CI stuff once we have it.

**Comment by cnuke** [comment]
I've pushed an updated `cbe` branch yesterday that cleans the `cbe_wip` branch up, somewhat at least. I am afraid it will lead to the same `gnatprove` errors you have already encountered on the wip branch but that's that.

Will you rebase your `gneiss` commits on top of my `cbe` branch or should I do the cherry-picking?

**Comment by m-stein** [comment]
@cnuke I have switched to my new cbe/merge_to_staging branch that is based on you most recent cbe/cbe_wip and rebased my so far existing clean-up commits onto it. The cbe test and cbe_vfs test are fine with this.

**Comment by m-stein** [comment]
I'll push future commits that shall be merged only via my cbe/merge_to_staging branch that I'll keep up-to-date for now with your cbe/cbe_wip branch, later with the cbe/staging branch.

PS: It seemed to me that your current cbe/cbe branch is quite outdated which was why I refrained from using it.

**Comment by senier** [comment]
> Will you rebase your `gneiss` commits on top of my `cbe` branch or should I do the cherry-picking?

We can decide later what is worth cherry-picking - just ignore those commits for now.

**Comment by cnuke** [comment]
@m-stein you are totally right, apparently I forgot to push the proper `cbe` branch (which is just `cbe_wip` without the VFS commits) - sorry for the inconvenience everyone.

@senier could you please use the updated branch (the head is d4bbbc538e9).

**Comment by m-stein** [comment]
@cnuke Thanks for updating your cbe/cbe branch! Unfortunately, when trying to rebase my cbe/merge_to_staging onto it, I noticed that the branch has regressions compared with your cbe/cbe_wip branch. Although, both branches contain the crypto-buffer commits, the cbe_vfs test compiles only on cbe/cbe_wip because cbe/cbe still uses the old API.

**Comment by senier** [comment]
@cnuke I guess then it would be wise then to wait until the tests used to work with cbe/cbe_wip also work with cbe/cbe before calling that the staging branch? Or is that unrelated?

**Comment by m-stein** [comment]
@cnuke @senier As a suggestion I've pushed my cbe/staging. It is cnuke/cbe + a small commit that fixes the cbe_vfs test. I've also re-based my cbe/merge_to_staging onto it with both tests working.

**Comment by cnuke** [comment]
@m-stein at this point I did not consider the VFS as vital (we have not decided yet which tests we actually want to execute), which is why I omitted the VFS API changes (partly because I already fixup'ed them into the VFS refactoring commit, my bad). AFAICT all currently relevant `CBE.Library` changes are part of my `cbe` branch, so from the initial CI and proving point of view I think the branch is fine. That being said, I have no objections to including your API adaption commit.

**Comment by senier** [comment]
@m-stein Great, thanks for the quick fix! IMHO the more tests are build and run the better. I'd suggest we leave the additional commit. I [applied our CI changes](https://github.com/Componolit/cbe/tree/staging) to m-stein/cbe/staging. Unless there are other issues, I'll push this state to cbe-project/cbe/staging.

As the proof CI works, I will close this ticket shortly. I'll open tickets on specific proof issues.

**Comment by m-stein** [comment]
I agree with @senier that the more tests run the better to avoid silent regression. Cool that you applied the CI changes right away Alex!

**Comment by senier** [comment]
Pushed to [cbe-project/cbe/staging](https://github.com/cbe-project/cbe/tree/staging).
