### ISSUE TITLE
Manage IO block-buffers outside of the CBE library

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#22]
This issue is analogous to issue #18 but for the communication block buffers with the IO back-end instead of the Crypto back-end.

**Comment by m-stein** [comment]
Fixed on my cbe/merge_to_staging branch. I changed the IO back-end API of the CBE library as follows **(this is meant only as proposal)**:

* ``Has_IO_Request``: Replaces former Has_IO_Data_To_Write and IO_Data_Required. In addition to the former procedures it also returns a data index. If the request is a "write", then the corresponding data is located in the IO-buffer slot referenced by the data index. Works similar to Crypto_Cipher/Plain_Data_Required for the crypto back-end.

* ``IO_Request_In_Progress``: Replaces former IO_Data_Read_In_Progress and Obtain_IO_Data (only the acknowledgement part). The new procedure takes only a data index as in parameter and acknowledges to the CBE that the outer world accepted the IO request behind the indicated IO-buffer slot and that the request is now in progress. Works similar to Crypto_Cipher/Plain_Data_Requested for the crypto back-end.

* ``IO_Request_Completed``: Replaces former Supply_IO_Data and Ack_IO_Data_To_Write. Takes a data index as in parameter for referencing the finished IO request and its IO-buffer slot, as well as a boolean whether the request was successful. If the request was a "read" and successful, the read data is expected to be present in the referenced IO-buffer slot. Works similar to Supply_Crypto_Cipher/Plain_Data for the crypto back-end.

Any opinions?

**Comment by cnuke** [comment]
Thanks for implementing handling I/O via data indices. I don't mind the interface changes, e.g. merging read and write path. The previous interface stems from a longish discussion we had after you did the initial translation from C++ to SPARK but apart from naming the functions/prodecures more clearly I don't recall any technical reasons for splitting them up.

**Comment by m-stein** [comment]
This issue is fixed on current master.
