### ISSUE TITLE
SPARK compliance

### ISSUE THREAD

**Issue by senier** [cbe-project/cbe#23]
The CI runs revealed some non-SPARK constructs in the current staging branch. The results can be reproduced locally by running the following command in the repository top-level (assuming the repository has been checked out recursively and `gnatprove` is installed):

```sh
$ make -f .ci/prove.mk prove_spark_ci
```

There are number of functions that have parameters of mode `in out`. This is forbidden in SPARK, as the result of a function with out parameters will depend on the order an expression is evaluated which may be implementation defined. Also, it would be really hard for the tools to analyze those function when being used in contracts.

The following functions are flagged as a violation of SPARK_Mode:

- [ ] Cache.Data_Index
- [ ] Library.Discard_Snapshot
- [ ] Library.Supply_Client_Data
- [ ] Write_Back.Peek_Generated_Cache_Update_PBA
- [ ] Crypto.Peek_Generated_Primitive

These functions need to be refactored to make the code valid SPARK.

**Comment by senier** [comment]
@cnuke @m-stein Any idea what it would take to make the above code SPARK-compliant?

**Comment by m-stein** [comment]
@senier I can give it a try today.

**Comment by senier** [comment]
> @senier I can give it a try today.

@m-stein Very much appreciated!

**Comment by m-stein** [comment]
@senier I have fixed the functions and the CI running on my cbe/merge_to_staging now and it seems that with the set gnatprove flags, there are a lot more complains (also "medium" and "low" ones). I'm thinking of removing the rare pre- and post-conditions that we already added (for now) as they are not part of a greater proving context anyway. What do you think?

**Comment by senier** [comment]
@m-stein Thanks for restructuring the code. What you're seeing is the default behavior of gnatprove, namely proving absence of runtime errors (we use no special flags here). It's expected that there are many open verification conditions when proving code for the first time. That's why we favor an incremental approach during development and keep our subprograms as small as possible.

I believe the code needs some refactoring to make verification feasible. A few subprograms are very long which is problematic: the SPARK tools perform modular verification at subprogram granularity. This is based on paths from the beginning to the return of the subprogram. With every conditional (if) statement in the program, you effectively double the number of paths that need to be proven. Eventually, the number of paths may be prohibitively large. Large subprograms will also make the process of proving the code a major pain, as you simply have to wait for the solvers most of the time. I'll open a separate ticket on that topic.

Don't be mislead by "medium" and "low" - *all* verification conditions need to be proved to show absence of runtime errors. Regarding the preconditions - I see not reason to remove them, unless you know they are wrong.

**Comment by m-stein** [comment]
@senier Thanks for your detailed explanation! I thought it might be a good idea to raise the bar for proving step by step. Like for example in a first step we would show only that the code is valid SPARK, in a second step absence of runtime errors, and in a third individual contracts. I wanted to show this first step before communicating my changes to you as my cbe/merge_to_staging commits might have added further SPARK_Mode violations. Therefore, I wanted to prevent the prove routine for now from distracting me with complains about pre and post conditions .

**Comment by m-stein** [comment]
On my cbe/merge_to_staging branch, when replacing in .ci/prove.mk the gnatprove switch ``--checks-as-errors`` with ``--mode=check_all``, the proving (``make -f .ci/prove.mk prove_spark_ci``) succeeds.

I didn't remove the pre/post conditions. But I tried to apply the Componolit approach of optional debugging code. I moved most of the debugging code to a separate package ``CBE.Debug`` and marked parts of it as ``SPARK_Mode => Off``. Also I made the call of the this code in the rest of the CBE dependent on the assertion policy ``Debug`` set in the new pragmas.adc file. This was necessary for proving.

**Comment by senier** [comment]
The proper flow is indeed (1) design/write code -> (2) SPARK compliance -> (3) Absence of runtime errors -> (4) functional correctness. After a while, points (1) and (2) will typically coincide, as you learn what's in the SPARK subset and avoid using other constructs. But not always, the aliasing rules, e.g. in conjunction with complex data structures, are not always straight forward.

It is advisable to apply this approach to small portions of you code (e.g. subprograms or packages) while you write them. The reason is that will need to get back to (1) when working on (2), (3) and (4). When you first do (1) for all of you code you may realize that you need to do fundamental changes in your design when working on (3) later. Also proving large portions of code after the fact tends to be a very tedious task (changing a small aspect of the code, waiting for the provers to finish, getting distracted with other stuff, changing the next apsect). The earlier you do this on small pieces of code, the less annoying it is.

We also observed that test unit cases often are vital for efficiently proving you code. The problem is the following. Assume you have to prove a subprogram `Foo`:

```Ada
procedure Foo (X : in out Integer) with
   Pre => My_Precodition (X),
   Post => My_Postcondition (X);
```

In the body of the subprogram you try to prove `My_Postcondition` from `My_Precodition` (let's assume both properties are not straight forward and the solvers cannot prove them automatically):

```Ada
procedure Foo (X : in out Integer) is
begin
   pragma Assert (My_Precodition (X));
   pragma Assert (...);
   pragma Assert (Contradiction);
   pragma Assert (...);
   pragma Assert (My_Postcondition(X));
end Foo;
```

In your proof you may add an assertion that is a contradiction (like "True = False", but typically it will look much less suspicious). From a false statement anything can be proven by contradiction, including all following assert statements and your postcondition. The only unproven statement left will be your contradiction, which you may leave for later. However, when realizing and removing the contradiction you still need to prove the postcondition.

Alternatively you may state your precondition in a way that is can never be fulfilled by the caller, but you don't realize that. You than use the too strong precondition to prove the desired postcondtion but the proof is essentially useless.

How can this issue be mitigated? By writing unit tests and executing the assertions, preconditions and postconditions with realistic data. If you precondition is too strong, you'll encounter an exception. When your assertion states a contradiction, it will also raise an exception. This will be very helpful to avoid introducing contradictions.

**Comment by senier** [comment]
> On my cbe/merge_to_staging branch, when replacing in .ci/prove.mk the gnatprove switch `--checks-as-errors` with `--mode=check_all`, the proving (`make -f .ci/prove.mk prove_spark_ci`) succeeds.

Note, that nothing is proven here. The `check_all` mode just checks compliance with the SPARK subset. No prove is performed, not even flow analysis to catch missing initialization etc. We never use this mode. 

> 
> I didn't remove the pre/post conditions. But I tried to apply the Componolit approach of optional debugging code. I moved most of the debugging code to a separate package `CBE.Debug` and marked parts of it as `SPARK_Mode => Off`. Also I made the call of the this code in the rest of the CBE dependent on the assertion policy `Debug` set in the new pragmas.adc file. This was necessary for proving.

Factoring out the debug code is a very good idea!

**Comment by m-stein** [comment]
@senier I very much appreciate that you share your experiences on verification in such a detailed and understandable way with us. I think this will help us a lot when diving deeper into the process.

> Note, that nothing is proven here. The check_all mode just checks compliance with the SPARK subset. No prove is performed, not even flow analysis to catch missing initialization etc. We never use this mode.

Thanks for mentioning the missing flow analysis. I only wanted to free the code from the most serious misbehavior in this first step and add this also to my regular QA before pushing a branch.

**Comment by m-stein** [comment]
@senier It seems that this issue is fixed on current master. May I ask you to close it?

**Comment by m-stein** [comment]
@senier I would really appreciate to see this issue closed as it publicly states that the CBE wouldn't be SPARK compliant yet, which is far from reality. I hope you can understand my discomfort with this.

**Comment by m-stein** [comment]
@senier Thanks a lot :)
