### ISSUE TITLE
Improve provability

### ISSUE THREAD

**Issue by senier** [cbe-project/cbe#24]
This ticket is a follow up to #23. @m-stein has updated the code to be valid SPARK. Next, the code should be refactored to make proving absence of runtime errors feasible. The following are considered problematic for proving (to be extended):

- [ ] Subprogram size
- [ ] Modular types

Large subprograms are inherently harder to prove and an annoyance while proving, as proof time is prolonged (cf. [this comment](https://github.com/cbe-project/cbe/issues/23#issuecomment-543785508)). In our experience, subprograms around 50 SLOC are favorable (unless, of cause, the nature of the problem dictates a larger subprogram).

Modular types are almost always a bad idea, as they are allowed to wrap which often makes proving them to be in a specific range very hard or impossible. They should only be used in situations where they are known to be always valid and when they are not used in calculations (directly).

**Comment by m-stein** [comment]
Thanks for documenting these issues!
Regarding the modular types there are already some commits on my cbe/merge_to_staging branch and I expect it to be finished in two weeks (I will be out of office next week).
I scheduled reducing the size of subprograms after the modular types.

**Comment by m-stein** [comment]
On my cbe/merge_to_staging, ``make -f .ci/prove.mk prove_spark_ci`` now succeeds when replacing ``--checks-as-errors`` with ``--mode=flow`` in .ci/prove.mk .

**Comment by jklmnn** [comment]
There is no need to remove `--checks-as-errors` since it only modifies the return code of gnatprove on unproved checks. The flow analysis also succeeds with this flag.

**Comment by m-stein** [comment]
@jklmnn Ah ok, thanks. I remember that with lower modes, the flag seemed to generate error output that was not of interest for me.

**Comment by m-stein** [comment]
@senier This issue remained inactive now for a long time. The outcome so far is that the whole CBE core logic passes gnatprove in mode "flow", modular types are only used when required, and a lot of long sub-programs were already split up. I sense that the next steps in this direction are worth their own issues when the time has come. But for now there are no plans to push it further. May I therefore ask you to close this issue?

**Comment by m-stein** [comment]
@senier While we're at it, could you please also consider closing this issue?

**Comment by m-stein** [comment]
@senier Thanks!
