### ISSUE TITLE
Get rid of Obtain_Client_Data_2

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#26]
The procedure ``Obtain_Client_Data_2`` is a dirty remnant for triggering the submit of a Block-IO read-primitive for each completed VBD primitive and it is part of the CBE library interface an must be called after each unsuccessful call of ``Obtain_Client_Data``. However, this trigger should be done internally during the ``CBE.Library.Execute`` call and the procedure should then be removed form the interface.

**Comment by m-stein** [comment]
This is now fixed on my cbe/merge_to_staging branch.

@cnuke Could you please review my solution? A more detailed history of this commit can be found on my cbe/merge_to_staging_2 branch if necessary (the tmp* commits).

**Comment by cnuke** [comment]
Awesome, thanks! I'll get right to it.

**Comment by m-stein** [comment]
This issue is fixed on current master.
