### ISSUE TITLE
client interface: fix and naming

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#28]
``Drop_Completed_Request`` currently doesn't take a request as indicator as the implementation merely drops the first completed request that it finds. Also, some function names of the client interface contain "client" and others not. I tend to add the term in general as done with the crypto and IO interface ("Crypto" and "IO").

**Comment by m-stein** [comment]
The two issues mentioned above are fixed on my cbe/merge_to_staging.

**Comment by m-stein** [comment]
This changes the interface of the CBE library as follows:

* ``Client_Request_Acceptable`` (former Request_Acceptable)
* ``Submit_Client_Request`` (former Submit_Request)
* ``Peek_Completed_Client_Request`` (former Peek_Completed_Request)
* ``Drop_Completed_Client_Request`` (former Drop_Completed_Request now with request as in parameter)
* ``Client_Data_Index`` (former Give_Data_Index)

__This is meant as proposal only__

**Comment by cnuke** [comment]
Thanks for doing the clean up, I integrated the commits.

**Comment by m-stein** [comment]
This issue is fixed on current master.
