### ISSUE TITLE
get rid of all avoidable mod types 

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#32]
Currently, a lot of types in the CBE are still modular types. This allows not only the values of these types to wrap but also are the ranges of these types often much bigger than required. Sometimes, unused parts of such a range are misused for mixing in additional meanings. Furthermore, I assume that proving code is harder with modular types and their flexibility involved. Therefore we should replace such types as far as possible with tailored ranges that cannot wrap.

**Comment by m-stein** [comment]
Fixed on my cbe/merge_to_staging branch.

@cnuke I have split-off two aspects (Index_Type, block address types) into separate commits as I'm not sure if the changes are desirable. What do you think?

**Comment by cnuke** [comment]
I don't mind applying those changes. However, the `Physical_Block_Address_Type` should not be bound to the maximal height of the tree as the address may point to any block on the physical block device, not only the virtual area covered by the tree.

**Comment by m-stein** [comment]
I pushed a new version to my cbe/merge_to_staging. Thanks for the review @cnuke.

**Comment by jklmnn** [comment]
Just as a general consideration:
Ranged types should be used everywhere where a specific range, arithmetic operations or similar things are important (e.g. indices, counts, offsets, etc). Modular types should be used where the value has no "logical" order but is just an arbitrary number. This is e.g. the case for the `Tag_Type` in #29 which afaik is not touched inside the cbe but only an arbitrary value that is supplied from the outside.

**Comment by m-stein** [comment]
Thanks for the hint. But is there a benefit in using a modular type over a range for a type that isn't subject to arithmetics anyway?

**Comment by m-stein** [comment]
I would rather tend to restrict flexibility further by disallowing arithmetics on the type..

**Comment by senier** [comment]
The best solution is to make the type private in a separate package. This must be a sibling package to the package where the type is used (say `CBE.Types`), as child packages have visibility to their parent package. The full type declaration can be a modular type again.

**Comment by m-stein** [comment]
This issue is fixed on current master.
