### ISSUE TITLE
ld: undefined reference to `memcmp' in SPARK code

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#36]
On my branch cbe/ld_undefined_reference_to_memcmp I trigger again a phenomenon that I observed several times during the last months. After I modified a src/lib/cbe/cbe-translation.adb the linker suddenly complains:
```
    LINK     cbe
/home/lypo/bin/genode/tool/19.05/bin/../lib/gcc/x86_64-pc-elf/8.3.0/../../../../x86_64-pc-elf/bin/ld: /home/lypo/genodelabs/genode/git/build/x86_64/var/libcache/cbe/cbe.lib.a(cbe-translation.o): in function `cbe__translation__execute':
/home/lypo/genodelabs/genode/git/repos/cbe/src/lib/cbe/cbe-translation.adb:206: undefined reference to `memcmp'

```
The error is not related to my changes, at least AFAICS. The code it complains about is a comparison of two array types:
```
if CBE_Hash /= Obj.Walk (Obj.Level).Hash then
```
In the past it just disappeared after some further unrelated changes to the file but this time I can't get rid of it.

**Comment by jklmnn** [comment]
This happens when the compiler needs to compare code larger than a register and cannot optimize it away. The symbol is usually expected to be provided by the runtime but it wasn't needed until now.
I added it in https://github.com/jklmnn/genode/commit/507677e76b54f97ba10defff87d28d1d59f52f24, so you can cherry pick it for now.

**Comment by m-stein** [comment]
Thanks @jklmnn for this quick patch. We tried the same beforehand, but it doesn't suffice. I assume that with this approach the symbol would have to be mentioned also in libports/lib/symbols/spark. But in general the question is whether we want to have such symbols in the ada runtime. If we later use Ada/SPARK components together with the Genode libc, chances are that we run into name clashes. Therefore, we quickfixed the issue by adding memcmp locally to the affected component. However, I see that this isn't a scalable solution.

Maybe there is a way of telling the compiler to not use memcmp? Because, when we revert the commit that triggered the error, we can see that the compiler does the same comparison of hashes without generating a call to memcmp.

**Comment by jklmnn** [comment]
Sorry, I thought about the symbols file when creating the patch but forgot to include it in the end.

I just checked the [GNAT documentation](https://docs.adacore.com/gnat_ugx-docs/html/gnat_ugx/gnat_ugx/the_gnat_configurable_run_time_facility.html#c-library). In short it says that even if you choose to neither link the runtime library nor a standard C library you still might have to provide `memcpy`, `bcopy`, `memmove`, `memcmp`, `malloc` and `free`. While it is relatively clear when `malloc` and `free` are used the requirement for the others seems to be highly dependent on what the compiler is deciding (on Muen we also had to implement `memcpy` and `memcmp`). I don't see a way to safely avoid this (without writing bad Ada to forcefully circumvent this).

As for a general solution, would a weak symbol in the runtime be sufficient to be linkable with the libc? Apart from that if you link the libc into your program the usefulness of a complexity-reduced runtime is at least questionable and you could use the full Ada runtime (which is world AFAIR) that uses the libc anyway.

**Comment by m-stein** [comment]
This issue is fixed (as clean as possible) on current master.
