### ISSUE TITLE
Program Error in cbe-translation.adb

### ISSUE THREAD

**Issue by jklmnn** [cbe-project/cbe#42]
I ran our throughput test against the CBE and noticed that the program error at https://github.com/cbe-project/cbe/blob/1aba57b06b97ce154a7cdf9fca6933148624f6d8/src/lib/cbe/cbe-translation.adb#L216 was triggered (usually between 100-200MB written). The log with tracing (at least what I could get from the setup as this was running on real hardware) is
```
Translation Level: 2 PBA: 9364 GOT: HASH (161, 284, 2, 145, 241, 216, 85, 215,...) EXP: HASH (176, 8, 112, 94, 126, 73, 184, 217,...)
Error: Exception raised: explicit raise in cbe-translation.adb:216
Error: Uncaught exception of type 'Ada::Exception::Program_Error'
```
The used cbe_block config was
```XML
<start name="cbe_block">
    <resource name="RAM" quantum="8G"/>
    <provides><service name="Block"/></provides>
    <config report="no" verbose="no" backing_size="6144M"
        vbd_size="2048M" vbd_outer_degree="64"
        ft_size="1M"   ft_outer_degree="64"
        initialize="yes">
    </config>
    <route>
        <service name="Report"> <child name="report_rom"/> </service>
        <any-service> <parent/> </any-service>
    </route>
</start>
```
The throughput test was sending 2MB requests and the system had 10G of memory available in total.

**Comment by cnuke** [comment]
Thanks for reporting, we'll try to reproduce it.

**Comment by cnuke** [comment]
@jklmnn could you please try if d80bb5f  fixes the problem in your test (you might have to apply ac8174d as well depending on the tree topology).

**Comment by jklmnn** [comment]
I added both commits to our staging and it fixed the problem.

**Comment by cnuke** [comment]
Thanks for testing, the commit will be part of the next PR.

**Comment by m-stein** [comment]
@jklmnn Is this issue still relevant? If not, may I ask you to close it?

**Comment by m-stein** [comment]
@jklmnn Thanks!
