### ISSUE TITLE
app/cbe_tester: add component for targeted testing

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#45]
Currently there is no way of testing directly on the CBE library interface. All tests access the CBe through additional abstraction levels like the block session or the VFS. A component that would directly incorporate the CBE library and processes scripted tests like the block tester would make debugging easier and more powerful.

**Comment by m-stein** [comment]
This is a first prototype of the CBE tester that is able to do replays of read/write/sync requests and create and discard snapshots:

fbee1ff app/cbe_tester: add component for targeted testing

**Comment by m-stein** [comment]
I pushed an updated version with 2 new commands for initializing a new CBE and checking an existing CBE. Both can also be used as self-standing components:

be7e7ad cbe_tester: disable back-end verbosity by default
06bc1fd cbe_check: as component + as command in cbe_tester
df230ee cbe_init: as component + as command in cbe_tester

**Comment by m-stein** [comment]
There's a new version of the cbe_tester on my cbe/merge_to_staging that adds the ``<dump/>`` command. The command currently dumps the whole CBE except snapshots and doesn't support any filters so far.

abf9ae5 cbe_tester: ``<dump/>`` command

**Comment by m-stein** [comment]
The newest version on my cbe/merge_to_staging checks and dumps all snapshots in contrast to the older versions and brings the first filter for ``<dump/>`` (``unused_nodes`` for switching whether unused snapshot slots, and invalid tree nodes shall be dumped).

c9ac25b cbe_tester: configure whether to dump unused nodes
87584d4 cbe_tester: check all snapshots
8802952 cbe_tester: dump all snapshots

**Comment by m-stein** [comment]
The cbe_tester ``<dump>`` command now provides further dump filters (defaults marked with star):
```
superblocks="all*|newest"
vbd="yes*|no"
free_tree="yes*|no"
```
0afeba0 cbe_tester: dump filters for SBs, FT, and VBD

**Comment by m-stein** [comment]
The newest version of the ``<dump/>`` command allows for limiting the size of the superblock backlog and the snapshot backlog and for dumping the hashes also. The new ``<dump/>`` parameters are ``max_superblocks``, ``max_snapshots``, ``hashes``. Let's say ``max_superblocks="3"`` and the newest superblock ID is 10, then only superblocks with IDs 10, 9, 8 would be dumped. Let's say ``max_snapshots="4"`` and the newest generation is 32, then only snapshots with generations 32, 31, 30, 29 would be be dumped. The former parameter ``superblocks`` has been replaced by ``max_superblocks``.

48a397e cbe_tester: dump filters max_superblocks, max_snapshots, hashes
8f12e24 cbe_tester: dump filters for superblocks, vbd, free_tree
e6c8aae cbe_tester: dump filter unused_nodes

**Comment by cnuke** [comment]
I merely skimmed your commit series but it looks really good - colour me impressed. I'll review them on monday. Thanks, so far.

**Comment by m-stein** [comment]
@cnuke Thanks for these kind words :)

Now, the ``<dump/>`` command supports also the filter ``vbd_pba`` for dumping only the parent and child nodes of a node with a specific PBA in the VBD.

29b5bb9 cbe_tester: dump filter vbd_pba

**Comment by m-stein** [comment]
The ``<dump>`` command now knows a VBA filter for the VBD and the the PBA filter config slightly changed:
```
<dump unused_nodes="no"
      max_superblocks="2"
      max_snapshots="2"
      vbd="yes"
      vbd_pba_filter_enabled="yes"
      vbd_pba_filter="38"
      vbd_vba_filter_enabled="yes"
      vbd_vba_filter="0x13"
      free_tree="no"
      hashes="no"/>
```
ec8c812 cbe_tester: dump filters vbd_pba_filter*, vbd_pba_filter*

**Comment by m-stein** [comment]
This issue is fixed on current master.
