### ISSUE TITLE
Redesign of the free-tree

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#47]
Recap: the free-tree (FT) is used to manage the sparse-nodes that can be utilized by the CBE in addition to VBD nodes. Whenever a non-volatile node (i.e. it is not part of the current generation) in the VBD needs to be overwritten (this includes inner as well as leaf nodes) a new block from the FT is requested. The old node is exchanged with the new one within the FT. The FT selects a usable block, i.e., a block either explicitly free or no longer referenced by any snapshot, to satisfy the VBD's request. However, since the FT is also a tree that employs a copy-on-write strategy, it might have to exchange its inner nodes as well in order to satisfy the request.

In the original design these nodes are selected from the FT itself. However, this leads to the problem that we have to decide when it's reasonable to use a particular branch in the tree. After all a leaf node might not reference enough usables nodes to update the branch and satisfy the request. So we have to check other branches as well until we have enough usable nodes to execute the update of the FT and satisfy the request. Since we do not know in advance how many branches may we have to query this is difficult to solve in a static fashion.

Therefor, @m-stein and I came up with a different approach that uses a third tree, the meta-tree (MT). It solely deals with managing the inner nodes (meta-data) of the FT. Whenever the FT needs to exchange one of its inner nodes it will ask the MT for a free node. Since the MT is dimensioned to hold all inner nodes of the FT, it is possible to completely rewrite the FT within one generation. As the MT only has to store the changes made within in the current generation, all nodes may be reused in the next generation. The precondition for the approach to work is that the topology (the number of entries in its leaf node is greater as the its height) of the MT allows the MT to replace an initially non-volatile branch completely with just one leaf node.

All in all that makes handling the FT more straightforward:

- The VBD wants to overwrite a branch and generates a request for the FT.
- The FT will scan its tree to look if it finds enough usable nodes in its leaf nodes to satisfy the request (otherwise snapshots have to be discarded). (At this point we do not care about non-volatile inner nodes as those are handled by the MT.)
- For every non-volatile node in the request the FT will exchange the node with one of its usable leaf node entries.
- For every non-volatile node in its own tree the FT will request a new node from the MT.
- The MT will first exchange all non-volatile nodes (all nodes not part of the current generation) and afterwards will exchange the FT node.

The downside of the approach is the addition of another tree and the increased space requirement in CBE but is from our point of view neglectable.

**Comment by cnuke** [comment]
My current `cbe_wip` branch contains the implementation of the new free-tree module as well as the meta-tree module. It is already integrated into @m-stein's current `merge_to_staging` branch, which includes his latest cache module changes.

**Comment by nfeske** [comment]
@cnuke Thanks a lot for the superb rehash of the problem and for documenting the rationale behind the MT.
