### ISSUE TITLE
CBE.Operation_Type: clean-up in preparation for re-keying

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#50]
Originally, primitives and requests represented the same common block operations (read, write, sync). However, other tasks like snapshot management and re-keying enter the field.

One consequence of this is that the concept of the CBE.Pool module evolved into a scheduler for all these activities and not only common block requests. This was done by simply extending the CBE.Request (instead of introducing some kind of new "Job" type that would reflect the "old" activities as well as the "new" ones and wrap CBE.Request).

That said, I would like to decouple request and primitive more from each other. This might be beneficial in another way too: Our experience with the concept of primitives so far shows that moving to target-module-specific primitive types might be a good idea, which would lead to a separation from requests anyway.

Eventually, a primitive would reflect only the different actions available at the module targeted by the primitive while a CBE request would reflect all actions available at the CBE front-end. As a first step into this direction and as a preparation for introducing the re-keying operation, the CBE.Operation_Type should be split up into CBE.Request_Operation_Type and CBE.Primitive_Operation_Type.

**Comment by m-stein** [comment]
These might be reviewed:

b097bea cbe: separate primitive and request operation (Primitive_Operation_Type)
2fa4c79 cbe: separate primitive and request operation (Request_Operation_Type)
79ca6be cbe: declare snapshot ops also in C++ Cbe::Request
f434a99 cbe: consider bad values in CXX enmumeration types

**Comment by cnuke** [comment]
Thanks for preparing the clean-up commit series, LGTM.

As a future step, we might as well simplify the library API and remove the distinct management interface (for now only `Create_Snapshot` and `Discard_Snapshot`), which would required additional changes to the `CBE.Request` though, eventually.

**Comment by nfeske** [comment]
That's very good to see! I very much appreciate you documenting those changes so carefully. Thanks for taking a step back and looking at the problem again with stronger typing in mind.

**Comment by m-stein** [comment]
Thanks for your feedback! Of course, I'd add commit descriptions as soon as it comes to merging.

**Comment by nfeske** [comment]
> Of course, I'd add commit descriptions as soon as it comes to merging.

I wasn't requesting any improvement but just wanted to praise your issue text. ;-)

**Comment by m-stein** [comment]
> I wasn't requesting any improvement but just wanted to praise your issue
> text. ;-)

No worries - It's in my own interest to do this.
