### ISSUE TITLE
Conventions: compiler warnings

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#6]
I don't know if this is desirable, but how about a convention to enable all reasonable GNAT compiler warnings and treat them as errors right from the beginning? If some of the them turn out to be not that sensible, it's an easy task to remove them again later. But the other way round can lead to loads of tedious adaption work in the aftermath.

For example, I'm currently using this prototype on my CBE working branches:
https://github.com/m-stein/genode/commit/520ee1fb4f9059d738248dbbd21edc76ae236632 Ada: strict warnings

**Comment by senier** [comment]
I fully agree that this is absolutely desirable and making style warnings errors will help to get used to them.  Enabling them early on (read: now) is a good idea, too - fixing loads of style warnings in existing code is little fun after all.

Below are the style options we came up for our projects over the years. Additionally, we should configure an `.adc` file using the `-gnatec` switch at the project level. The `.adc` should at least contain the line `pragma SPARK_Mode (On);` to enforce the SPARK subset by default. We'll probably need to set other things like the desired overflow policy and assertion mode there.

```
abstract project Switches
is
   Compiler_Switches :=
   (
      "-gnatA"	 -- Avoid processing gnat.adc, if present file will be ignored

     ,"-gnatef" -- Full source path in brief error messages

     ,"-gnateV" -- Validity checks on subprogram parameters
     ,"-gnatf"  -- Full errors. Verbose details, all undefined references
     ,"-gnatU"  -- Enable unique tag for error messages

     -- Validity checks
     ,"-gnatVa" -- turn on all validity checking options

     -- Warnings
     ,"-gnatwa" -- turn on all info/warnings marked with + in gnatmake help
     ,"-gnatwe" -- treat all warnings (but not info) as errors
     ,"-gnatwd" -- turn on warnings for implicit dereference
     ,"-gnatwh" -- turn on warnings for hiding declarations
     ,"-gnatwk" -- turn on warnings for standard redefinition
     ,"-gnatwt" -- turn on warnings for tracking deleted code
     ,"-gnatwu" -- turn on warnings for unordered enumeration

     -- Style checks
     ,"-gnaty3"    -- Check indentation (3 spaces)
     ,"-gnatya"    -- check attribute casing
     ,"-gnatyA"    -- check array attribute indexes
     ,"-gnatyb"    -- check no blanks at end of lines
     ,"-gnatyc"    -- check comment format (two spaces)
     ,"-gnatyd"    -- check no DOS line terminators
     ,"-gnatye"    -- check end/exit labels present
     ,"-gnatyf"    -- check no form feeds/vertical tabs in source
     ,"-gnatyh"    -- check no horizontal tabs in source
     ,"-gnatyi"    -- check if-then layout
     ,"-gnatyI"    -- check mode in
     ,"-gnatyk"    -- check casing rules for keywords
     ,"-gnatyl"    -- check reference manual layout
     ,"-gnatyL8"   -- check max nest level < nn
     ,"-gnatyM120" -- check line length <= nn characters
     ,"-gnatyn"    -- check casing of package Standard identifiers
     ,"-gnatyO"    -- check overriding indicators
     ,"-gnatyp"    -- check pragma casing
     ,"-gnatyr"    -- check casing for identifier references
     ,"-gnatys"    -- check separate subprogram specs present
     ,"-gnatyS"    -- check separate lines after THEN or ELSE
     ,"-gnatyt"    -- check token separation rules
     ,"-gnatyu"    -- check no unnecessary blank lines
     ,"-gnatyx"    -- check extra parentheses around conditionals

   );

end Switches;
```

**Comment by m-stein** [comment]
The convention is enforced by the Genode toolchain used for current master.

**Comment by m-stein** [comment]
We could create a more sophisticated '.adc' file for the project as well but this should be done in a dedicated issue.
