### ISSUE TITLE
Make the trust-anchor an external component

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#61]
The _trust-anchor_ (_TA_) is currently part of the `CBE.Library`. It plays a vital role in attesting the _CBE_ and might be implemented in different ways, e.g., as hardware dongle. To provide this kind of flexibilty the _TA_ is replaced by an API in the `CBE.Library`. This API is used by an external component to provide the _TA_ service to the library.

This interface is modelled after the modul interface and looks as follows:

* **`Peek_Generated_TA_Request`** get currently pending request

* **`Drop_Generated_TA_Request`** acknowledge given request

* **`Peek_Generated_TA_SB_Hash`** get hash value for pending _Secure_Superblock_ request

* **`Peek_Generated_TA_Key_Ciphertext_value`** get ciphertext key value for pending _Encrypt_Key_ request

* **`Peek_Generated_TA_Key_Plaintext_value`** get plaintext key value for pending _Decrypt_Key_ request

* **`Mark_Generated_TA_Create_Key_Request_Complete`** mark request as complete while passing in plaintext key value
* **`Mark_Generated_TA_Secure_SB_Request_Complete`** mark request as complete
* **`Mark_Generated_TA_Decrypt_Key_Request_Complete`** mark request as complete while passing in plaintext key value
* **`Mark_Generated_TA_Encrypt_Key_Request_Complete`** mark request as complete while passing in ciphertext key value

For the time being, this external component re-uses the exsting _TA_ implementation.

**Comment by cnuke** [comment]
The following commit series implements the necessary changes:

39ed529 - external: create common package definition
4574bf2 - cbe: extract the TA part 0 (TA request)
81fd12b - cbe: extract the TA part 1 (move back into cbe)
bfb2d79 - cbe: extract the TA part 2 (add interface)
6920e4c - cbe: extract the TA part 3 (adapt TA module)
7da6b9d - cbe: extract the TA part 4 (use TA in library)
73fabb1 - cbe: extract the TA part 5 (move back to cbe_common)
686cab0 - cbe: extract the TA part 6 (cxx library)
ac0c202 - cbe: extract the TA part 7 (C++ header)
ddb4280 - external_trust_anchor: initial implementation (library)
7f47e92 - external_trust_anchor: initial implementation (cxx)
4bf265b - cbe_init: add TA interface (library)
c023f2b - cbe_init: add TA interface (cxx library)
5f6e132 - cbe_init: add TA interface (C++ header)
6ff8394 - cbe_init: use external TA (app)
eeab906 - vfs/cbe: use external ta library

**Comment by m-stein** [comment]
@cnuke Thanks for this very clean commit series! I merely had to add the missing empty external.mk file. The adaption of cbe_tester was a no-brainer that worked out of the box. I've merged the commits to staging.

**Comment by cnuke** [comment]
@m-stein thanks for merging. My bad for having omitted the .mk file.

**Comment by m-stein** [comment]
@cnuke This has just entered the master branch. So, the issue might be closed.
