### ISSUE TITLE
Generate 'ada_main' package for shared objects without build system flag

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#64]
Currently, the invokation of the Gnatbinder to generate the ``ada_main`` package for a shared object must be triggered via a build system flag ``LIB_ADAINIT`` that was introduced into the Genode build system only for this purpose. The ``ada_main`` package is required when having elaboration code (e.g. for the secondary stack or global statics). So far, it is uncertain whether a build system flag is a good approach which is why the flag hasn't entered Genode master yet. That said, we tend to another CBE-repo-local solution. We would like to introduce a new Make include file ``<CBE_REPO>/lib/mk/generate_ada_main_pkg.inc`` that triggers the generation of ``ada_main`` when included by the CBE libraries. In Genode, on the other hand, the corresponding features like elaboration code and a secondary stack will be unsupported for the time being.

**Comment by cnuke** [comment]
Commit af54956 contains the required change and makes the corresponding commit in the Genode repository obsolete. It should be sufficient for the current CBE code, i.e., it will se up the secondary stack for the runtime. Since it operates solely on `dummy.ads` it probably will not be useful for elaboration stuff.

**Comment by cnuke** [comment]
The commits 59a66c6, ca46f1c and e048478 replace the former commit. Now all C++ facing CBE related libraries are treated as SAL and provide there own `init` and `final` procedures.

**Comment by m-stein** [comment]
@cnuke Thanks a lot for fixing this! It has reached master now. Could you please close the issue?

**Comment by m-stein** [comment]
@cnuke Nevermind! Didn't realize the issue was mine...
