### ISSUE TITLE
Provide recipes for CBE components

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#65]
For the last demo we relied on a shell script that created all required archives. This works fine when manually managing the archives but really is nothing more than a stop-gap solution.

With the changes done in #64 in place it is straight-forward to provide proper packaging. After all, from the system's point of view, i.e., using the CBE in Sculpt, we can hide the fact that most parts but the glue code of the CBE are written in SPARK. And by that do not have to deal with the peculiarities of Ada (see #63).

**Comment by cnuke** [comment]
The commits above prepare and clean up the existing code and provide the recipes. This branch depends on the changes of #64 (it is based on that branch) and my current [20.08-cbe](/cnuke/genode/commits/20.08-cbe) branch.

**Comment by m-stein** [comment]
@cnuke Thank you for this clean commit series! It has just entered the master branch. So, the issue might be closed.
