### ISSUE TITLE
Write-through cache module

### ISSUE THREAD

**Issue by cnuke** [cbe-project/cbe#7]
The cache module stores the `Block_data` for a given primitive. Read primitives are served from its internal cache whereas _write_ primitves will always be passed on to next module and will invalidate the internal cache. In case it does not handle _write_ primitves the internal cache must be invalidated manually.
It implements the following interface:

**`primitve_acceptable`** returns true if the primitive can be handled.

**`submit_primitve`** adds the given primitive to the cache.

**`peek_generated_primitive`** returns the next generated primitve. In case there is no primitive pending, a invalid primitive is returned. Depending on the type of primitive, i.e., _read_ or _write_, the next suitable module can be checked.

**`take_generated_primitive`** returns the next generated primitive and marks it as _in progress_. Must only be called when `peek_generated_primitive` has returned a valid primitive.

**`mark_completed_primitive`** marks the given primitive as completed. In case it is a _read_ primitive the internal cache will be filled.

**`peek_completed_primitive`** returns the next completed primitive. In case there is no primitive pending, a invalid primitive is returned. Depending on the type of primitive, i.e., _read_ or _write_, the next suitable module can be checked.

**`take_completed_primitive`** returns the next completed primitive. Must only be called when `peek_generated_primitive` has returned a valid primitive.

**`mark_as_invalid`** invalidates the given primitive and thereby corresponding internal cache entry. This function is used by the bus if the cache module does not handle _write_ primitives.

**Comment by nfeske** [comment]
I wonder, why does the cache deal with "requests"? Isn't it dealing with primitives only? I would not have expected the term "request" as part of the cache's interface.

**Comment by cnuke** [comment]
Yes, that is indeed the case - every occurrence of `request` should be replaced with `primitive` (BTDT).

**Comment by senier** [comment]
> In case it does not handle _write_ primitves the internal cache must be invalidated manually.

The interface looks good to me in general. However, I don't understand the above statement - in which cases does the cache *not* handle write requests?

**Comment by cnuke** [comment]
The bus may choose to pass on the write primitives directly to the I/O module depending on how the modules are sticked together. In this case it is the job of the bus to manage the cache.

**Comment by senier** [comment]
Just for clarification: is the *bus* the main loop calling all the `peek_*`/`take_*`/etc. operations of the modules (the same thing as the *data-flow pipeline* in #3)?

I still can't wrap my head around what would be a situation where the cache is bypassed by the bus, but still needs to be managed. Do you have an example?

**Comment by cnuke** [comment]
Yes, the bus is the mainloop.

The situation would be if the cache is intentionally only used for read primitives and write primitives do not replace existing cache entries or rather invalidate them and therefor must be managed from the outside. That being said, I don't think this particular module, especially how it operates, will be of much value in the CBE in the end and is merely documented for completeness' sake.

**Comment by senier** [comment]
I see. Thanks for the clarification!
