### ISSUE TITLE
Remove additional code authored by Componolit

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#71]
@senier @jklmnn 

There is some code that was authored by Componolit and that does not form part of the CBE base libraries. As far as I can tell this comprises the gneiss server in ``src``, the plotting python scripts in ``tool``, and the ``.travis.yml`` file. As with the Genode-specific code (#70), I would like to remove this code from the CBE repository as it is not fundamental for using the CBE and tailored to a specific integration scenario.

If you're still interested in this code, I would suggest that you move it to a dedicated repository as I did with the Genode-related code. What do you think?

**Comment by m-stein** [comment]
@senier @jklmnn 
This would be the corresponding commit:

6f8470e Remove additional code authored by Componolit

**Comment by senier** [comment]
> If you're still interested in this code, I would suggest that you move it to a dedicated repository as I did with the Genode-related code. What do you think?

I'm OK with removing the code. We'll move it to a dedicated repo when needed.

**Comment by m-stein** [comment]
@senier @jklmnn Thank you for the fast feedback!

I have also removed the ``.ci`` directory now, at least for Genode, an adapted CI fits far better. There is the ``<genode>/tool/cbe_autopilot`` tool that also does the GNAT-prove part but directly uses the ``<genode>/contrib/libsparkcrypto-<version>`` dir for the LSC sources and the Genode build directory for LSC installation and object dir.

**Comment by m-stein** [comment]
Fixed on master.
